image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install and Setup QIIME 2
    init: |
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
      rm Miniconda3-latest-Linux-x86_64.sh
      echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $HOME/.bashrc
      source $HOME/.bashrc
      conda init bash
      source $HOME/.bashrc
      conda update -n base -c defaults conda
      conda env create -n qiime2-amplicon-2024.5 --file https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml
      echo 'eval "$(conda shell.bash hook)"' >> $HOME/.bashrc
      echo 'conda activate qiime2-amplicon-2024.5' >> $HOME/.bashrc
      echo 'source $(which tab-qiime)' >> $HOME/.bashrc
    command: |
      source $HOME/.bashrc
      echo "QIIME 2 environment activated and tab completion enabled. Try typing 'qiime i' and press Tab."
      qiime --help

vscode:
  extensions:
    - ms-python.python
