image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Conda and QIIME 2
    init: |
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
      rm Miniconda3-latest-Linux-x86_64.sh
      echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $HOME/.bashrc
      echo '. $HOME/miniconda/etc/profile.d/conda.sh' >> $HOME/.bashrc
      echo 'conda activate qiime2-amplicon-2024.5' >> $HOME/.bashrc
      source $HOME/.bashrc
      conda init bash
      conda update -n base -c defaults conda
      conda env create -n qiime2-amplicon-2024.5 --file https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml
    command: |
      source $HOME/.bashrc
      echo "Conda and QIIME 2 setup complete. Verifying installation..."
      conda info
      qiime --version
      echo "Setup complete. You can now use QIIME 2 commands."

vscode:
  extensions:
    - ms-python.python

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
